// Auth
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

// Cracks
export const VIEW_CRACKS = "VIEW_CRACKS";
export const VIEW_CRACK_INFO = "VIEW_CRACK_INFO";
export const RESET_CRACK_INFO = "RESET_CRACK_INFO";